### ISSUE TITLE
Support for symlinks in git repo

### ISSUE THREAD

**Issue by kincl** [rundeck-plugins/git-plugin#1]
It looks like the git plugin when checking out a repository with symlinks does not create the symlink on the filesystem but instead just creates a file with the destination which I think is what git is tracking internally.

**Comment by ltamaster** [comment]
Hi @kincl ,

I tested the plugin using a symlink and it worked OK, can you share your job or explain further your use case.

Thanks
Luis

**Comment by kincl** [comment]
Hi @ltamaster 

Sure so here is a simple job that shows what I am talking about. In the example b.txt should be a symlink to test1/a.txt. The repo is https://github.com/kincl/test-symlinks

```
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: 941e4e18-95c4-46b0-8da7-99f149c29dea
  loglevel: INFO
  name: test-symlinks
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        gitBaseDirectory: /tmp/test-symlinks
        gitBranch: master
        gitUrl: ssh://git@github.com/kincl/test-symlinks
        strictHostKeyChecking: 'no'
      nodeStep: false
      type: git-clone-step
    - script: |-
        #!/bin/bash
        ls -l /tmp/test-symlinks
        cat /tmp/test-symlinks/b.txt
        file /tmp/test-symlinks/b.txt
    keepgoing: false
    strategy: node-first
  uuid: 941e4e18-95c4-46b0-8da7-99f149c29dea
```
